apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: qkafkaproducer
  name: qkafkaproducer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qkafkaproducer
  template:
    metadata:
      labels:
        app: qkafkaproducer
    spec:
      containers:
      - name: qkafkaproducer
        image: burrsutter/qkafkaproducer:1.0.0
        ports:
          - containerPort: 8080
        resources:
          requests: 
            memory: "40Mi" 
            cpu: "250m" 
          limits:
            memory: "40Mi"
            cpu: "250m" 
        livenessProbe:
          httpGet:
              port: 8080
              path: /health
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 2          
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3
